### ISSUE TITLE
Syntax highlight in JS/TS string literals

### ISSUE THREAD

**Issue by ivan-kleshnin** [albertoventurini/graphdb-intellij-plugin#26]
Hello Alberto. 

First let me say **Thank You** for forking this plugin 🙏  I wish you enough time, energy and interest to support it!

I imagine you have a lot of tasks to finish before you can even review our proposals... but still, if you don't mind, I'd like to add one.

---

It would be great to have syntax highlight not only in `.cypher` files but in `.js / .ts` as well. In realistically large projects some queries are inevitably dynamic (DRY):

```ts
import {FetchTaskLabel} from "../Graph"

export const MATCH_TASKS = (label: FetchTaskLabel) => `
  MATCH (u:User)-[:NEEDS]->(t:${label})
  WITH u, collect(t) AS ts
  WHERE NOT u.login IN $exceptLogins
  AND size(ts) = 1
  UNWIND ts AS t
  RETURN u, t
  SKIP $skip
  LIMIT $limit
`
```

This particular query can't really be stored in `query.cypher`, only in `query.ts`.

---

In GraphQL world this is solved by adding `gql` tags which often do nothing except signaling the syntax to the parser:

```ts
import {gql} from "graphql-request"

// Below query is properly highlighted in WebStorm (in case a corresponding plugin is installed)
export const FETCH_FOLLOWERS_PAGE = gql`
  query ($login: String!, $limit: Int!, $cursor: String) {
    user(login: $login) {
      followers(first: $limit, after: $cursor) {
        nodes {
          login
        }
        pageInfo {
          endCursor
          hasNextPage
        }
        totalCount
      }
    }
  }
`
```

I imagine you could eventually publish a library with no-op `cypher` tag.

```ts
import cypher from "cypher-tag" // (s: string) => string

// Now parser knows the string below is a CYPHER code
export const QUERY = cypher`
   ...
`
```

---

Sorry if you don't use TS/JS yourself, it's just our JS-centrism in play.

**Comment by albertoventurini** [comment]
Hi Ivan,

Thank you for logging this issue, and I'm glad you're finding this plugin fork useful!

When I want to accomplish what you described in IntelliJ Idea, I use language injection (https://www.jetbrains.com/help/idea/using-language-injections.html). I just need to add a comment such as:
```
// language=Cypher
```
before my string, and then Idea treats it as a cypher fragment with full syntax highlighting and autocompletion etc. Does the same work in Webstorm? Or are you describing a different feature?

Thank you!

**Comment by ivan-kleshnin** [comment]
Oh, wow, I somehow never heard of this feature, until today. Thank you for sharing!  

> Or are you describing a different functionality?

No, exactly this one. It works, and whether it's comment-based or decoration-based – I don't care. Closing as done 😄
