### ISSUE TITLE
round() with precision

### ISSUE THREAD

**Issue by j3ns** [albertoventurini/graphdb-intellij-plugin#50]
Please support [round(expression, precision)](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-numeric/#functions-round2) and [round(expression, precision, mode)](https://neo4j.com/docs/cypher-manual/current/functions/mathematical-numeric/#functions-round3) for Neo4j.

**Comment by albertoventurini** [comment]
Hi @j3ns, I created issue #55 to address this. Currently, the plugin contains hardcoded definitions for several Neo4j functions, including `round`. These hardcoded definitions are out of date. The solution is to rather rely on the output of the `SHOW FUNCTIONS` command, which returns (amongst others) all the valid signatures for `round`.

**Comment by albertoventurini** [comment]
Hi @j3ns, the latest version of the plugin (v0.5.0) has been released. It includes support for new function signatures, including `round()`. Could you please try it and let me know what you think? Thank you

**Comment by j3ns** [comment]
Thank you for the fast solution! It seems to be solved with v0.5.0 to me.
