### ISSUE TITLE
CREATE INDEX = error

### ISSUE THREAD

**Issue by neopaf** [albertoventurini/graphdb-intellij-plugin#61]
```cql
CREATE INDEX FieldPK IF NOT EXISTS FOR (field:Field) ON (field.name);
```
Causes error. Maybe it is not hard to change grammar to accept these?

![Снимок экрана 2023-01-24 в 11 10 43](https://user-images.githubusercontent.com/4362564/214241321-81ec25a2-827f-4630-a254-793a395d1e18.png)

(Thanks for FANTASTIC plugin!)

**Comment by albertoventurini** [comment]
Hi @neopaf, thank you for logging this issue!
Support for new `CREATE INDEX` syntax was added in version 0.4.0 of the plugin. Which version are you using? It looks like it's working correctly on my side (I'm using version 0.5.0 of the plugin)

<img width="727" alt="Screenshot 2023-01-28 at 15 53 54" src="https://user-images.githubusercontent.com/5089391/215270193-2cdf3f01-68bc-4973-8328-8a5f5a91bd69.png">

**Comment by neopaf** [comment]
![Снимок экрана 2023-02-06 в 09 44 25](https://user-images.githubusercontent.com/4362564/216901637-8218901a-c383-4f7f-b8ce-6856aeb21d1e.png)
thanks, Alberto. Looks like I was using an outdated version somehow.
(Shame on me for not double-checking before reporting)
(Thanks to you for your patience ;)
