### ISSUE TITLE
Not compatible with the version of your running IDE (IntelliJ IDEA 2023.1)

### ISSUE THREAD

**Issue by vekit-cn** [albertoventurini/graphdb-intellij-plugin#69]
When I switch idea version 2023.3 -> 2023.1 (toolbox version)
How can I fix it?

**Comment by albertoventurini** [comment]
I have created a new release which supports IntelliJ 2023.1. Please find it here: https://github.com/albertoventurini/graphdb-intellij-plugin/releases/tag/v0.6.1

It should be published on the JetBrains servers within a few days. Meanwhile, it can be installed manually with the zip available at the URL above.

**Comment by albertoventurini** [comment]
The new version of the plugin (0.6.1), which is compatible with IntelliJ 2023.1, is now available on the JetBrains servers. I'll go ahead and mark this issue as closed. Thanks!
