### ISSUE TITLE
No releases since version 0.5.0 

### ISSUE THREAD

**Issue by rluvaton** [albertoventurini/graphdb-intellij-plugin#70]
Great plugin!

There are no new releases since version 0.5.0, even though the code changed with new releases

I suspect the publish and release script is not running, this cause us to not be able to upgrade DataGrip
- #69 

even when a fix has been merged:
- 942e6f0

**Comment by albertoventurini** [comment]
Hi @rluvaton, thank you for opening an issue about this. I am aware that the plugin is currently not working on newer versions on IJ - I just need to find the time to fix it. I am hoping to release a new version within a few days. The commit you referenced did upgrade the plugin version, but it is throwing an exception against new versions of IJ, so I didn't want to create a release until that exception is fixed.

**Comment by albertoventurini** [comment]
I have created a new release which supports IntelliJ 2023.1. Please find it here: https://github.com/albertoventurini/graphdb-intellij-plugin/releases/tag/v0.6.1

It should be published on the JetBrains servers within a few days. Meanwhile, it can be installed manually with the zip available at the URL above.

**Comment by rluvaton** [comment]
Thank you for the quick fix!

**Comment by albertoventurini** [comment]
My pleasure! I'll go ahead and close this issue for now, please feel free to comment if there's anything I've missed.
