### ISSUE TITLE
Not compatible with IntelliJ IDEA 2023.2 EAP

### ISSUE THREAD

**Issue by villesau** [albertoventurini/graphdb-intellij-plugin#75]
Looks like the plugin is not compatible with the latest EAP.

**Comment by oyvindwe** [comment]
Is it really necessary to have an upper limit on supported version? This requires a plugin release for every minor version of IntelliJ.

**Comment by albertoventurini** [comment]
@oyvindwe The downside of that approach is, it will keep working until it doesn't. That's what happened to the old plugin developed by Neueda - it doesn't have an upper limit, so technically it can be installed on today's version of IntelliJ. (It won't work though.)

On the other hand, I hear you - it is not a great user experience having to wait for a fix when a new version of IJ is released.

The best approach is to proactively add support for the next version (EAP) before it is released, so as to be ready ahead of time. My apologies, I will try to do that next time.

For now, PR https://github.com/albertoventurini/graphdb-intellij-plugin/pull/77 adds support for IJ 2023.2. I'll merge into main and prepare a new package when the build is finished.

**Comment by albertoventurini** [comment]
A new patch release of the plugin is available here: https://github.com/albertoventurini/graphdb-intellij-plugin/releases/tag/v0.6.2

It will take a day or two to show up on JetBrain's servers, so until then, please download it from the above link and install the plugin manually from disk.

**Comment by albertoventurini** [comment]
A new version of the plugin is now available from JetBrain's marketplace (https://plugins.jetbrains.com/plugin/20417-graph-database) and it should be possible to upgrade directly from IntelliJ and other IDEs. I'll go ahead and close this issue.
